#!/usr/bin/env bash

# This script accepts simple messages from the command line
#   and sends them to you as pushover messages

APP_TOKEN=''
USER_KEY=''

curl -s \
  -F "token=$APP_TOKEN" \
  -F "user=$USER_KEY" \
  -F "message=$1" \
  https://api.pushover.net/1/messages.json
